apiVersion: v1
kind: Namespace
metadata:
  name: rhods-notebooks

---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: s2i-minimal-notebook
spec:
  template:
    spec:
      containers:
        - name: s2i-minimal-notebook
          image: quay.io/thoth-station/s2i-minimal-notebook:v0.2.2
          imagePullPolicy: Always
          env:
            - name: NOTEBOOK_ARGS
              value: "--NotebookApp.token='' --NotebookApp.password=''"

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: s2i-minimal-notebook
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: s2i-minimal-notebook
    weight: 100
  port:
    targetPort: http-s2i-minimal-notebook
  wildcardPolicy: None
