apiVersion: v1
kind: Namespace
metadata:
  name: rhods-notebooks
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notebook-editor
#  namespace: rhods-notebooks
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notebook-editor-anyuid
#  namespace: rhods-notebooks
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - anyuid
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notebook-editor-anyuid
#  namespace: rhods-notebooks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notebook-editor-anyuid
subjects:
  - kind: ServiceAccount
    name: notebook-editor
---
apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  annotations:
    notebooks.kubeflow.org/server-type: jupyter
  name: ephemeral-nb-server
#  namespace: rhods-notebooks
  labels:
    app: ephemeral-nb-server
spec:
  template:
    spec:
      containers:
        - env: []
          image: >-
            public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter-scipy:master-6e4ad3b4
          imagePullPolicy: IfNotPresent
          name: ephemeral-nb-server
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: '0.5'
              memory: 1Gi
          volumeMounts: []
      serviceAccountName: notebook-editor
      tolerations: []
      volumes: []
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ephemeral-nb-server
#  namespace: rhods-notebooks
spec:
  to:
    kind: Service
    name: ephemeral-nb-server
    weight: 100
  port:
    targetPort: http-ephemeral-nb-server
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

