---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: odh-dashboard-cluster-admin
subjects:
  - kind: ServiceAccount
    name: odh-dashboard
    namespace: odh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
