apiVersion: v1

kind: Secret
metadata:
  name: storage-config
stringData:
  localMinIO: |
    {
      "type": "s3",
      "access_key_id": "AKIAIOSFODNN7EXAMPLE",
      "secret_access_key": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
      "endpoint_url": "http://minio.controller_namespace:9000",
      "default_bucket": "modelmesh-example-models",
      "region": "us-south"
    }
